name: Update README.md

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: r-lib/actions/setup-r@v2
      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          packages: any::rvest
      - name: Compute README.md
        run: | 
          library(rvest)
          writeLines(
            gsub(
              pattern = "movies \\([0-9,]*\\) and",
              replacement = read_html("https://www.imdb.com/user/ur56341222/ratings") %>%
                html_nodes("div.header.filmosearch") %>%
                html_text() %>%
                gsub(".*\\(of ([^)]*)\\).*", "movies (\\1) and", .),
              x = readLines("README.md")
            ),
            con = "README.md"
          )
        shell: Rscript {0}
      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v4
        with:
          commit-message: "ci: automatic update"
          signoff: false
          branch: auto-detected-updates
          delete-branch: true
          title: "Automatic update"
      - name: Merge Pull Request
        uses: juliangruber/merge-pull-request-action@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          number: ${{ steps.cpr.outputs.pull-request-number }}
          method: merge

